apiVersion: v1
kind: Service
metadata:
  name: utility
  labels:
    app: utility
spec:
  selector:
    app: utility
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility
  labels:
    app: utility
spec:
  selector:
    matchLabels:
      app: utility
  template:
    metadata:
      labels:
        app: utility
    spec:
      containers:
      - name: utility
        image: some.docker.registry/utility:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "256m"
            memory: "768M"
          limits:
            cpu: "768m"
            memory: "768M"
      securityContext:
        runAsUser: 1000
